/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceUsd' : IDL.Text,
  'formats' : IDL.Text,
  'isBestSeller' : IDL.Bool,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Text,
  'whatsapp' : IDL.Text,
  'items' : IDL.Text,
});
export const CustomRequest = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'description' : IDL.Text,
  'budget' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'whatsappNumber' : IDL.Text,
  'storeName' : IDL.Text,
  'heroText' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, Product], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCustomRequests' : IDL.Func([], [IDL.Vec(CustomRequest)], ['query']),
  'getOrdersByWhatsapp' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'isAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, Order], [], []),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'submitCustomRequest' : IDL.Func([IDL.Text, CustomRequest], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceUsd' : IDL.Text,
    'formats' : IDL.Text,
    'isBestSeller' : IDL.Bool,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Text,
    'whatsapp' : IDL.Text,
    'items' : IDL.Text,
  });
  const CustomRequest = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'description' : IDL.Text,
    'budget' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'whatsappNumber' : IDL.Text,
    'storeName' : IDL.Text,
    'heroText' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, Product], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCustomRequests' : IDL.Func([], [IDL.Vec(CustomRequest)], ['query']),
    'getOrdersByWhatsapp' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'isAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, Order], [], []),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'submitCustomRequest' : IDL.Func([IDL.Text, CustomRequest], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
